---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ASUS.
--- DateTime: 2025/11/3 20:58
---
-- 1. 参数列表
-- 1.1 优惠券ID
local voucherId = ARGV[1]
-- 1.2 用户ID
local userId = ARGV[2]
-- 1.3 订单ID
local orderId = ARGV[3]

-- 2. 数据KEY
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId
-- 3. Lua脚本业务逻辑
-- 3.1 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2 库存不足，返回下单失败，1
    return 1
end
-- 3.3 判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 3.4 用户已经下单，返回下单失败，2
    return 2
end
-- 3.5 扣减库存
redis.call('incrby', stockKey, -1)
-- 3.6 下单，将用户加入set集合
redis.call('sadd', orderKey, userId)
-- 3.7 发送消息到队列中
redis.call('xadd', 'stream.orders', '*','userId', userId, 'voucherId', voucherId, 'id', orderId)
-- 3.8 返回下单成功，0
return 0